import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  reportSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Case Studies',
      className: 'sidebar-case-studies',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Steady State',
          href: '/multisensory-experience/creative-opportunities-playing-with-expectation#case-study-steady-state',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Current, Rising',
          href: '/multisensory-experience/creative-opportunities-boosting-presence#case-study-current-rising',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Abba Voyage',
          href: '/in-focus-vision#case-study-abba-voyage',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Arcade',
          href: '/in-focus-hearing#case-study-arcade',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Water Droplets',
          href: '/in-focus-touch#case-study-water-droplets',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'In Pursuit of Repetitive Beats',
          href: '/in-focus-touch/practical-insights-3#case-study-in-pursuit-of-repetitive-beats',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: "Jeff Wayne's War of the Worlds",
          href: '/in-focus-touch/practical-insights-3#case-study-jeff-waynes-the-war-of-the-worlds-the-immersive-experience-layered-reality-london',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: "The Matrix in 'Shared Reality'",
          href: '/in-focus-sense-of-space#case-study-the-matrix-in-shared-reality',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Disney HoloTile Floor',
          href: '/in-focus-sense-of-space#case-study-disney-holotile-floor',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Managing the Bubble in Onboarding',
          href: '/in-focus-personal-and-peripersonal-space#case-study-managing-the-bubble-in-onboarding',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'Body of Mine',
          href: '/in-focus-proprioception-and-body-map#case-study-body-of-mine',
          className: 'sidebar-case-study-item',
        },
        {
          type: 'link',
          label: 'LED Wrist-bands',
          href: '/in-focus-interactivity#case-study-led-wrist-bands',
          className: 'sidebar-case-study-item',
        },
      ],
    },
  ],
};

export default sidebars;
